services:
  postgres:
    image: postgres:16
    container_name: codesstellar-postgres
    environment:
      POSTGRES_DB: codesstellar_dev
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - codesstellar_postgres_data:/var/lib/postgresql/data

volumes:
  codesstellar_postgres_data:
